version: 1.0
app:
  maven:
    groupId: "libertyDefaultApplication"
    artifactId: "libertyDefaultApplication"
    version: "1.0.1"
    type: ear
  instances:
    min: 10
    max: 10
  endpoints: public
