version: 1.0
app:
  maven:
    groupId: "libertyDefaultApplication"
    artifactId: "libertyDefaultApplication"
    version: "1.0.1"
    type: ear
  instances:
    min: 1
    max: 1
  # List of variables that can be referenced in the server.xml
  variables:
    - name: some_liberty_variable_name
      value: "some_liberty_variable_value"
      
